### ISSUE TITLE
POLIGONA

### ISSUE THREAD

**Issue by DEMOOH** [nartallax/minecraft#1]
Товарищ, нужна ваша помощь с лаунчером.
Вот адрес конфы: 
https://discord.gg/V9ARdDr

**Comment by nartallax** [comment]
Ну охуеть теперь.
В смысле, у меня есть куча контактов с очевидными адресами - почта nartallax@gmai.com, вконтакт vk.com/nartallax, а вы мне пишете через гитхаб. Это еще ладно, но при этом еще даете ссылку на... что? это какой-то новый мессенджер?
Короче, жаждете коммуникации - пишите на два вышеупомянутых контакта, ну или прямо тут. Ебаться с еще какими-то мессенджерами мне влом.
